import { Navbar } from "../components/Navbar";

const SECTIONS = [
  {
    title: "1. Acceptance of Terms",
    content: `By creating a SkyNode account or using the SkyNode application, you agree to be bound by these Terms of Use. If you do not agree, please do not register or use the service.

SkyNode is a bachelor-project web application developed for academic purposes at FERI, University of Maribor. It is not a commercial product. These terms govern your use of the platform at the deployed URL: https://sky-node-three.vercel.app/`,
  },
  {
    title: "2. Description of Service",
    content: "SkyNode is an AI-assisted travel planning platform. It allows users to:",
    bullets: [
      "Search for flights and explore estimated prices",
      "Discover destinations using maps, weather, and destination data",
      "Generate AI-powered itinerary suggestions",
      "Save, share, and collaborate on trip plans",
      "View live flight radar data",
      "Communicate with other users within shared trip contexts",
    ],
    footer:
      "SkyNode is a planning and discovery tool. It does not sell airline tickets, issue bookings, or provide official travel advice.",
  },
  {
    title: "3. Account Registration",
    content: "To access personalised features, you must create a free account using a valid email address. You agree to:",
    bullets: [
      "Provide accurate information when registering",
      "Keep your password secure and not share it with others",
      "Notify the development team if you suspect unauthorised access to your account",
      "Be responsible for all activity under your account",
    ],
    footer:
      "You must be at least 16 years old, or the minimum age required by applicable law in your country, to create an account. By registering, you confirm that you meet this requirement.",
  },
  {
    title: "4. Acceptable Use",
    content: "You agree to use SkyNode only for lawful purposes and in a way that does not infringe the rights of others. You must not:",
    bullets: [
      "Use the service to distribute spam, harmful content, or malware",
      "Attempt to access other users' accounts or data without authorisation",
      "Interfere with or disrupt the operation of SkyNode or its infrastructure",
      "Scrape, copy, or reverse-engineer the application for commercial purposes",
      "Upload or share content that is illegal, offensive, or violates third-party rights",
      "Use the AI assistant to generate content that is harmful, misleading, or abusive",
    ],
  },
  {
    title: "5. Disclaimers",
    subsections: [
      {
        title: "5.1 Flight and Price Information",
        content:
          "Flight results, prices, and availability displayed in SkyNode are retrieved from third-party providers and may not reflect real-time or final booking prices. SkyNode does not guarantee accuracy, completeness, or availability. Always verify pricing and availability on official airline websites or authorised booking platforms before making any purchase.",
      },
      {
        title: "5.2 AI-Generated Content",
        content:
          "Itineraries, suggestions, and recommendations generated by the AI assistant are for informational purposes only. They may contain inaccuracies, outdated information, or unsuitable recommendations. Do not rely solely on AI-generated content for travel decisions. Always verify travel requirements (visas, entry restrictions, safety advisories) through official government or airline sources.",
      },
      {
        title: "5.3 Live Flight Data",
        content:
          "Live flight radar data is sourced from OpenSky Network and may be delayed, incomplete, or unavailable. It is provided for informational use only and should not be used for navigation or safety-critical purposes.",
      },
      {
        title: "5.4 Service Availability",
        content:
          "SkyNode is provided on an \"as is\" and \"as available\" basis. We do not guarantee uninterrupted availability. The service may be offline for maintenance, updates, or due to third-party service disruptions.",
      },
    ],
  },
  {
    title: "6. Intellectual Property",
    content: `The SkyNode application, its design, and its code are developed as part of an academic project at FERI, University of Maribor. All original content and code remain the property of the development team.

Third-party services, APIs, and libraries used within SkyNode remain the intellectual property of their respective owners. SkyNode does not claim ownership of any third-party content.

You retain ownership of the travel data, trips, and content you create within SkyNode.`,
  },
  {
    title: "7. Limitation of Liability",
    content:
      "To the fullest extent permitted by applicable law, SkyNode and its developers are not liable for:",
    bullets: [
      "Losses arising from incorrect or outdated flight information",
      "Financial losses from bookings made based on SkyNode data",
      "Damages resulting from reliance on AI-generated itineraries or recommendations",
      "Loss of data due to technical failures or service interruptions",
      "Third-party service failures that affect SkyNode functionality",
    ],
    footer:
      "Your use of SkyNode is at your own discretion and risk. This limitation applies regardless of the legal theory under which any claim is brought. To the maximum extent permitted by law, SkyNode provides no warranties, express or implied, regarding the accuracy, reliability, or availability of the service.",
  },
  {
    title: "8. Privacy",
    content:
      "Your use of SkyNode is also governed by our Privacy Policy, which is incorporated into these Terms of Use by reference. By using SkyNode, you consent to the data practices described in the Privacy Policy.",
  },
  {
    title: "9. Account Termination",
    content: `You may delete your account at any time through the Account Settings page. Upon deletion, we will make reasonable efforts to remove your personal data from our systems, except where retention is required for security, legal, or technical reasons.

We reserve the right to suspend or terminate accounts that violate these Terms of Use, without prior notice.`,
  },
  {
    title: "10. Changes to These Terms",
    content:
      "We may revise these Terms of Use from time to time. The effective date at the top of this document will be updated when changes are made. Continued use of SkyNode following any changes constitutes your acceptance of the updated terms.",
  },
  {
    title: "11. Governing Law",
    content:
      "These Terms of Use are governed by the laws of the Republic of Slovenia. Any disputes arising in connection with these terms shall be subject to the jurisdiction of the competent courts in Slovenia.",
  },
  {
    title: "12. Contact",
    content:
      "For any questions about these Terms of Use, please contact the SkyNode development team through your academic institution at FERI, University of Maribor.",
  },
];

type Subsection = {
  title: string;
  content: string;
  bullets?: string[];
};

type Section = {
  title: string;
  content?: string;
  bullets?: string[];
  footer?: string;
  subsections?: Subsection[];
};

function BulletList({ items }: { items: string[] }) {
  return (
    <ul className="mt-2 space-y-1.5 pl-4">
      {items.map((item, i) => (
        <li key={i} className="flex gap-2 text-slate-700 text-sm leading-relaxed">
          <span className="mt-1.5 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-blue-500" />
          <span>{item}</span>
        </li>
      ))}
    </ul>
  );
}

function TermsSection({ section }: { section: Section }) {
  return (
    <section className="border-b border-slate-100 pb-8 last:border-0">
      <h2 className="mb-3 text-lg font-bold text-slate-900">{section.title}</h2>

      {section.content && (
        <p className="text-sm leading-relaxed text-slate-700 whitespace-pre-line">{section.content}</p>
      )}

      {section.bullets && <BulletList items={section.bullets} />}

      {section.subsections?.map((sub, i) => (
        <div key={i} className="mt-5">
          <h3 className="mb-1.5 text-sm font-semibold text-slate-800">{sub.title}</h3>
          <p className="text-sm leading-relaxed text-slate-700">{sub.content}</p>
          {sub.bullets && <BulletList items={sub.bullets} />}
        </div>
      ))}

      {section.footer && (
        <p className="mt-3 text-sm leading-relaxed text-slate-700">{section.footer}</p>
      )}
    </section>
  );
}

export function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <Navbar />
      <main className="mx-auto max-w-4xl px-6 pt-24 pb-16">
        <header className="mb-10 text-center">
          <h1 className="text-3xl font-black text-slate-900">Terms of Use</h1>
          <p className="mt-2 text-sm text-slate-600">
            Effective: June 2026 &nbsp;·&nbsp; SkyNode — AI-Assisted Travel Planning
          </p>
        </header>

        <div className="space-y-8">
          {SECTIONS.map((section, i) => (
            <TermsSection key={i} section={section as Section} />
          ))}
        </div>

        <footer className="mt-12 rounded-lg bg-slate-50 px-6 py-4 text-center text-xs text-slate-500">
          This applies to the SkyNode application deployed at{" "}
          <a
            href="https://sky-node-three.vercel.app/"
            className="text-blue-600 hover:underline"
            target="_blank"
            rel="noreferrer"
          >
            sky-node-three.vercel.app
          </a>
          . For questions, contact the SkyNode team at FERI, University of Maribor.
        </footer>
      </main>
    </div>
  );
}

export default TermsPage;